name: Test

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update_release_draft:
    runs-on: ubuntu-22.04
    steps:
        - name: checkout
          uses: actions/checkout@v4
        - name: setup go
          uses: actions/setup-go@v5
          with:
            go-version-file: .go-version
        - name: compile
          run: |
            source .buildkite/scripts/common.sh
            add_bin_path
            with_mage
            make -C go -f "Makefile.debian11" build

